# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/MainDesign/MainDesign.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign || ORIG_REF_NAME==MainDesign} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_ClockDivider_0_0/MainDesign_ClockDivider_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_ClockDivider_0_0 || ORIG_REF_NAME==MainDesign_ClockDivider_0_0} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_ClockDivider_1_0/MainDesign_ClockDivider_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_ClockDivider_1_0 || ORIG_REF_NAME==MainDesign_ClockDivider_1_0} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_ClockDivider_2_0/MainDesign_ClockDivider_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_ClockDivider_2_0 || ORIG_REF_NAME==MainDesign_ClockDivider_2_0} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_ClockDivider_3_0/MainDesign_ClockDivider_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_ClockDivider_3_0 || ORIG_REF_NAME==MainDesign_ClockDivider_3_0} -quiet] -quiet

# XDC: bd/MainDesign/MainDesign_ooc.xdc
